### ISSUE TITLE
Translator erro message output

### ISSUE THREAD

**Issue by leouk** [overturetool/vdm-vscode#127]
Hi Jonas,

Wondered how/where the translation error messages would appear in the extension? Couldn't quite find where they were.

Best,
Leo

**Comment by nickbattle** [comment]
@leouk Do we still need an answer to this?

**Comment by leouk** [comment]
Yes. I haven't worked out where this is, but likely inside vdm2isa-lsp project, which is now separate from vdm2isa. I am focusing on extending vdm2isa with recursion and improve templating. But we are yet to show how this percolates up to VSCode messages.

**Comment by nickbattle** [comment]
So to progress this, we need to know what sort of errors we're talking about. Are you asking how to raise errors? Or what happens to errors reported a particular way?

The LSP server returns any messages you return from handling the UnknownTranslationEvent, so that can include translation errors - ie. you could highlight translation problems in the source. There's a `LSPMessageUtils` class, which may help by turning `VDMMessages` into JSON responses, though perhaps it's most useful as an example of what to do!

**Comment by leouk** [comment]
Okay. At the moment, the vdm2isa (VDMJ) plugin simply keeps tabs of errors and warnings, just like the VDMJ type checker does. So, the need on how to "list" these errors/warnings within the VSCode output window. Where is a good example of this?

Yes, the option to turn VDMMessages into LSP ones is the need. And also, the various kinds of VDMMessages within the translator. If you look at vdm2isa.messages.VDM2IsaMessage, you will see that (somewhat like VDMJ type checker), there are ranges of message numbers depending on the kind of problem. Some might be irreconsible, others can be easily pointed back to  the VDM source, etc.

**Comment by nickbattle** [comment]
I should probably add a section on this in the Plugin Writer's Guide. I've never tried it, but the responses from event handlers are definitely sent back to the UI.

So have a look at `LSPMessageUtil`. There are some methods on that which take a list of VDMMessage and a set of files (though that can be omitted). It returns an RPCMessageList that you just add to your own responses (if any). That should be all you need to do. The messages should be marked on the screen and Problems view, and should get cleared at the next type check.

I'd like to know whether/how this works, because obviously it's quite an important feature for plugins.

**Comment by nickbattle** [comment]
I think this was eventually resolved, @leouk ? Closing... we can re-open if you need to.
