### ISSUE TITLE
Issue with ChessWayRT example project

### ISSUE THREAD

**Issue by FrederikPM** [overturetool/vdm-vscode#180]
The VDM-RT example project `ChessWayRT` cannot be handled by the extension.

Looking at the server log there are two null pointer exceptions being reported.
[See attached log](https://github.com/overturetool/vdm-vscode/files/8966695/ChessWayRT_lang_server.log).

**Comment by nickbattle** [comment]
Oops! OK, thanks for the log. I'll take a look later, though NPEs are
usually easy to spot.

**Comment by nickbattle** [comment]
These were NPEs in the typechecker, which is unusual (since you have to typecheck the specs, so we usually notice these). I guess no one has even opened this model in a while.

I've pushed a fix to "development".

The model now, superficially, looks the same as Overture, though I would have to compare the detailed logs and timings to be sure. Both of them stop eventually with a `Periodic threads overlapping in 'Controller'` error. That may be a genuine problem with the model though.

**Comment by FrederikPM** [comment]
Ah okay. 
Yeah my understanding of these example projects is that they might not have been looked at/used by anyone in a long time.

That sounds great. I'll just close this issue then?

**Comment by nickbattle** [comment]
Yes, I think a genuine problem was fixed, so we can close this.

I noticed that "find references" seems to have a problem with this spec, but I'll open another issue for that.
