### ISSUE TITLE
Type binding is not supported in the interpreter

### ISSUE THREAD

**Issue by cakemaster9001** [overturetool/vdm-vscode#206]
In chapter 8 of the VDM++ language manual (pages 95 and 96), it is possible to do type binding. This is done with the syntax "pattern" ":" "type", and the example is:
```
{ y | y : nat & y > 3 }
```
When the example is run in the interpreter, it gives an Error 4 exception, which says it cannot bind values for the 'nat' type. I tested it with the following code:
```
class TestComp
operations
/* Works just fine */
public pure testNormalSetComp : set1 of nat ==> set of nat
testNormalSetComp(inp) == return {x | x in set inp & x < 3};

/* Will fail with error 4 */
public testOpTypeComp : () ==> set of nat
testOpTypeComp() == return { y | y : nat & y < 3 };

/* Will fail with error 4 */
public pure testOpPureTypeComp : () ==> set of nat
testOpPureTypeComp() == return { y | y : nat & y < 3 };

functions
/* Will fail with error 4 */
public testFunTypeComp : () -> set of nat
testFunTypeComp() == { y | y : nat & y < 3 };

end TestComp
```
The regular set comprehension works as expected, but the type bindings fail with the same error.
The tests have also been tested with "y > 3" and a custom type with an invariant to limit the range of valid values, but all the different examples fail.

**Comment by mortenhaahr** [comment]
This appears to also fail with map comprehension

**Comment by nickbattle** [comment]
Yes, this is a limitation with all interpretive VDM tools (VDMTools is the same). The problem is that we have to completely evaluate sets (or maps or sequences) before applying the predicate limitation, and with a type bind the set/seq/map membership is infinite. Roughly, the interpreter process gets every value of the bind, applies the predicate and populates the result with the ones that pass; the problem is in the first step!

But it will work with finite types, like `bool` or `<OK>` and types constructed from finite types. So `bool * bool` would work, as does `set of bool` (but not `seq of bool`, which is infinite). Unions of finite types are also finite, like `<YES> | <NO> | <MAYBE>`.

Overture used to have a clunky process for letting you specify (say) an int range that a integer bind would expand to. But that was really awkward to use and I never included it in VDMJ.

Infinite binds are allowed in the VDM _language_, but only when qualified by a predicate that limits the sets - the language theory requires finite sets, I believe, though PGL would know more about that. So from a theoretical analysis perspective you can write them and they are meaningful, but the interpreter will fail.

I'm afraid there's not much I can do about the issue therefore.

**Comment by nickbattle** [comment]
Footnote 6 on p14 of the LRM says, "Notice that type bindings over infinite types (discharging the invariant limitations) cannot be executed by the VDM interpreters because in general they are not executable (see section 8 for further information about this)."

Section 8 adds, "Notice that type binds can only be executed by the VDM interpreters in case the type can be deduced to be finite statically. This would require the VDM interpreters to search through infinite domains like the natural numbers."

But if you can think of an efficient way to compute a finite subset of an infinite type using a predicate, let me know :-)

**Comment by nickbattle** [comment]
This function is useful for experimenting with what's possible:
```
functions
	sizeOf[@T]: () +> nat1
	sizeOf() == card { x | x : @T };
```
So for example:
```
p sizeOf[bool]()
= 2
Executed in 0.033 secs.

p sizeOf[bool * bool]()
= 4
Executed in 0.021 secs.

p sizeOf[bool * <OK> | <FAIL>]()
= 3
Executed in 0.045 secs.

p sizeOf[map bool to <OK> | <FAIL>]()
= 5
Executed in 0.035 secs.

p sizeOf[nat]()
Error 4: Cannot get bind values for type nat in 'DEFAULT' (/home/nick/vscode.tests/TestSL/test.vdmsl) at line 3:19
Execution terminated.
```

**Comment by nickbattle** [comment]
If you're wondering about some of these(!), try it without the `card`:
```
p { x | x : map bool to <OK> | <FAIL> }
= {<FAIL>, {false |-> <OK>, true |-> <OK>}, {false |-> <OK>}, {true |-> <OK>}, {|->}}
Executed in 0.029 secs.
```
:-)

**Comment by nickbattle** [comment]
So can we close this? It is working as expected and the LRM does document the limitations.

**Comment by cakemaster9001** [comment]
That makes a lot of sense; I had overlooked the footnote :)
If I think of a way to limit the infinite sets with the predicate I will discuss it with you in the future.

Thank you for your time!
