### ISSUE TITLE
Overloading beyond subclass

### ISSUE THREAD

**Issue by f-ishikawa** [overturetool/vdm-vscode#220]
# Overview

Overloading, or defining operations with the same name but different input parameters, does not work if it is done over a superclass and a subclass.
Is this intended/correct or a bug?

# Version

VDM VSCode v1.3.7

# How to reproduce

```
class Test

operations
    
public op1 : () ==> ()
op1() == skip;

end Test

class Test2 is subclass of Test

operations
    
public op1 : int ==> ()
op1(x) == skip;

public useOp1_error : () ==> ()
useOp1_error() == op1();
-- This op1 calls is said error "op1 in not scope". If we remove the above op1 with int, this call works.

public useOp1_nonerror : () ==> ()
useOp1_nonerror() == op1(1);

end Test2
```

**Comment by nickbattle** [comment]
Thanks for reporting this. I will take a look, but from memory, I tried to make the VDM++ overload/override behaviour like C++ rather than Java. So an override will replace all overloads from the superclass (as C++), rather than just overriding the one method (Java). But that's just from memory and there might be a bug :-)

The error message could definitely be better, if that is the case.

I'm about to take a short break, but I'll check how this works next week.

**Comment by nickbattle** [comment]
This might help:

https://stackoverflow.com/questions/1628768/why-does-an-overridden-function-in-the-derived-class-hide-other-overloads-of-the

**Comment by f-ishikawa** [comment]
Ah, I now got it is a possible design choice. Thanks! (you may close if necessary)

**Comment by nickbattle** [comment]
I checked the way the typechecker does this. I'm not 100% sure it is bug free(!), but the issue you reported is deliberate. So I'll close this issue, but if you spot other unexpected overload/override behaviour, I'll look again.
